services:
  - type: web
    name: inventory-api
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt && python manage.py migrate"
    startCommand: "gunicorn inventory_project.wsgi:application"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
